version: '3'
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: tp1
    volumes:
      - ./scripts:/scripts

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always # OR: on-failure