- name: TP1 Backup DB
  hosts: victim

  tasks:
  - name: Permissions on file
    file:
      path: tp1/scripts/backup-db.sh
      mode: 'u+x'
  
  - name: Execute backup script
    shell: cd tp1; docker-compose exec db sh scripts/backup-db.sh