- name: TP1 Backup DB
  hosts: dev

  tasks:
  - name: Permissions on file
    file:
      path: tp1/scripts/backup-db.sh
      mode: 'u+x'
  
  - name: Execute backup script
    shell: cd tp1; docker-compose exec db sh scripts/backup-db.sh
    
  - name: List dump files
    shell: ls -Art tp1/dump | tail -n 1
    register: dumpfile
    tags:
      list-dump-files

  - debug: var=dumpfile
    tags:
      list-dump-files

  - name: Fetch dump file
    fetch:
      src: tp1/dump/{{ dumpfile.stdout }}
      dest: dump/{{ ansible_hostname }}-{{ dumpfile.stdout }}
      flat: yes # pas de création d'arborescence correpondant à la structure du remote node
    tags:
    - fetch-file

  # - name: Fetch toto file
  #   fetch:
  #     src: /tmp/demo/bem.txt
  #     dest: dump
  #     flat: no
  #   tags:
  #   - fetch-file

  